exports.STATUS_PENDING = "PENDING";
exports.STATUS_ACCEPTED = "ACCEPTED";

exports.AUTH_USER = "AUTH_USER";
exports.UNKNOW = "UNKNOWN";
exports.FRIEND = "FRIEND";
exports.REQUESTER = "REQUESTER";
exports.RECEIVER = "RECEIVER";
